version: '3.8'
services:
  go2rtc:
    container_name: go2rtc
    image: alexxit/go2rtc:latest
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config  # 挂载配置文件路径